Issue-#32-Doc-update Readme
SoffanG17/SoffanG17 pull request #33
Opened 2021-02-11 15:26 UTC by Sebberh

Closes #32

2021-02-11 20:19 UTC, hengque requested changes
I think you might have meant to write the contribution under your name

2021-02-11 20:19 UTC, hengque commented on README.md
```suggestion
###### Sebastian Fagerlind
Communicating with GitHub API
Remaking code skeleton with updated libs
Documentation & tests

```

2021-02-12 09:35 UTC, EleonoraBorzis commented on README.md
test

2021-02-12 09:36 UTC, EleonoraBorzis commented on README.md
test

2021-02-12 12:46 UTC, merged